### ISSUE TITLE
Getting the import error

### ISSUE THREAD

**Issue by sahil210695** [trailbehind/DeepOSM#78]
python bin/run_analysis.py
Traceback (most recent call last):
File "bin/run_analysis.py", line 7, in 
from src.run_analysis import analyze, render_results_as_images
File "/DeepOSM/src/run_analysis.py", line 6, in 
import label_chunks_cnn_cifar
File "/DeepOSM/src/label_chunks_cnn_cifar.py", line 11, in 
import tflearn
File "/usr/local/lib/python2.7/dist-packages/tflearn/init.py", line 21, in 
from .layers import normalization
File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/init.py", line 10, in 
from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, 
File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/recurrent.py", line 8, in 
from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, 
**ImportError: No module named core_rnn**

and this 

  File "bin/run_analysis.py", line 7, in <module>
    from src.run_analysis import analyze, render_results_as_images
  File "/DeepOSM/src/run_analysis.py", line 6, in <module>
    import label_chunks_cnn_cifar
  File "/DeepOSM/src/label_chunks_cnn_cifar.py", line 11, in <module>
    import tflearn
  File "/usr/local/lib/python2.7/dist-packages/tflearn/__init__.py", line 4, in <module>
    from . import config
  File "/usr/local/lib/python2.7/dist-packages/tflearn/config.py", line 5, in <module>
    from .variables import variable
  File "/usr/local/lib/python2.7/dist-packages/tflearn/variables.py", line 7, in <module>
    from tensorflow.contrib.framework.python.ops import add_arg_scope as contrib_add_arg_scope
**ImportError: cannot import name add_arg_scope**

while running the github project https://github.com/zilongzhong/DeepOSM
In this one I am able to create training data successfully but not able to run_analysis.py and while running I'm getting this error and

**Comment by andrewljohnson** [comment]
That looks like an old fork.

I suggest you delete your installed code, clone the top-level repo (this one), and try again.

**Comment by sahil210695** [comment]
ya but i want solution for that !! @andrewljohnson
