### ISSUE TITLE
Pillow version is low, cause error when saving JPEG files

### ISSUE THREAD

**Issue by andrewjavao** [trailbehind/DeepOSM#79]
I met this error when I rendering findings to JPEG, using `render_results_for_analysis` method in file `src/training_visualization.py`, traceback:
`Wrong JPEG library version: library is 90, caller expects 80`
`Traceback (most recent call last):`
`  File "upload_data.py", line 31, in <module>`
`    main()`
`  File "upload_data.py", line 27, in main`
`    render_findings(raster_data_paths, model, training_info, model_info['bands'], True)`
`  File "/DeepOSM/src/s3_client_deeposm.py", line 30, in render_findings`
`    training_info['tile_size'])`
`  File "/DeepOSM/src/training_visualization.py", line 34, in render_results_for_analysis tile_size)`
`  File "/DeepOSM/src/training_visualization.py", line 54, in render_predictions`
`    predictions=predictions_by_naip)`
`  File "/DeepOSM/src/training_visualization.py", line 111, in render_results_as_image`
`    im.save(outfile, "JPEG")`
Upgrade Pillow python library version to 4.0.0 can solve this.

btw, Since  deeposm.org site no longger exists, so can you provide codes that generates local website contents? Is there ways to view the results other than JPEG with findings on map?

**Comment by andrewljohnson** [comment]
I was investigating #75 this weekend, and I decided:

a) there is an issue saving JPEGSs (probably this issue here)
b) the warning displayed in console under #75 is unrelated and maybe mostly
harmless

I consider this issue to be important... it sucks that the JPEGs aren't
rendering. This is my top priority for fixing.

**Comment by andrewljohnson** [comment]
Please open this as a separate issue and let's discuss: "btw, Since deeposm.org site no longger exists, so can you provide codes that generates local website contents? Is there ways to view the results other than JPEG with findings on map?"
